In [1]:
!pip3 install torch torchvision
!pip3 install matplotlib

In [3]:
#Librería base
import torch
import numpy as np
#Fijamos la semilla para asegurar reproducibilidad 
torch.manual_seed(42)

# Crear tensores

In [10]:
# --- MÉTODO 1: Desde Datos Crudos (Listas) ---
# El más básico. Convertir una lista de Python a Tensor.
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Desde lista:\n{x_data} \n tiene dimension { x_data.shape } \n su tipo de dato es {x_data.dtype}\n")

Desde lista:
tensor([[1, 2],
        [3, 4]]) 
 tiene dimension torch.Size([2, 2]) 
 su tipo de dato es torch.int64



In [11]:
# --- MÉTODO 2: Desde NumPy (El puente con Data Science) ---
# Típico en negocios: Pandas -> NumPy -> PyTorch
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"\nDesde NumPy:\n{x_np} \n tiene dimension { x_np.shape } \n su tipo de dato es {x_np.dtype}\n")


Desde NumPy:
tensor([[1, 2],
        [3, 4]]) 
 tiene dimension torch.Size([2, 2]) 
 su tipo de dato es torch.int64



In [12]:
# --- MÉTODO 3: Inicialización Aleatoria o Constante ---
# Crucial para inicializar los PESOS de la red neuronal antes de entrenar.
shape = (2, 3) # 2 filas, 3 columnas

rand_tensor = torch.rand(shape) # Números aleatorios (0 a 1)
ones_tensor = torch.ones(shape) # Todo unos
zeros_tensor = torch.zeros(shape) # Todo ceros

print(f"\nAleatorio (para pesos iniciales):\n{rand_tensor} \n tiene dimension { rand_tensor.shape } \n su tipo de dato es {rand_tensor.dtype}\n")


Aleatorio (para pesos iniciales):
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) 
 tiene dimension torch.Size([2, 3]) 
 su tipo de dato es torch.float32



In [20]:
# --- MÉTODO 4: Desde otro Tensor ---
# Crear un nuevo tensor basado en las propiedades de uno existente.
tensor_ones = torch.ones_like(x_data) # Crea un tensor de unos con la misma forma y tipo que x_data
tensor_rand = torch.rand_like(x_data, dtype=torch.float) # Crea un tensor aleatorio con la misma forma que x_data pero con tipo float
print(f"\nDesde otro tensor (unos):\n{tensor_ones} \n tiene dimension { tensor_ones.shape } \n su tipo de dato es {tensor_ones.dtype}\n")
print(f"\nDesde otro tensor (aleatorio):\n{tensor_rand} \n tiene dimension { tensor_rand.shape } \n su tipo de dato es {tensor_rand.dtype}\n")


Desde otro tensor (unos):
tensor([[1, 1],
        [1, 1]]) 
 tiene dimension torch.Size([2, 2]) 
 su tipo de dato es torch.int64


Desde otro tensor (aleatorio):
tensor([[0.9346, 0.5936],
        [0.8694, 0.5677]]) 
 tiene dimension torch.Size([2, 2]) 
 su tipo de dato es torch.float32



# Operaciones básicas

In [ ]:
# acceso a elementos
element = x_data[0, 1]  # Accede al elemento en la primera
print(f"Elemento en (0,1): {element}")


Elemento en (0,1): 2


In [14]:
# Suma de tensores
tensor_sum = x_data + x_data
print(f"Suma de tensores:\n{tensor_sum}")

Suma de tensores:
tensor([[2, 4],
        [6, 8]])


In [16]:
# multiplicación de tensores como matrices
tensor_product = x_data @ x_data
print(f"Producto de tensores:\n{tensor_product}")

Producto de tensores:
tensor([[ 7, 10],
        [15, 22]])
